services:
  postgres:
    image: postgres:17
    container_name: shotify-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shotify
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
